baseurl = "https://yanjiyu.com"
#baseurl = "https://heuristic-hoover-bc51cc.netlify.com"
title = "Jiyu"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
enableEmoji = true
googleAnalytics = "UA-165971391-1"
enableGitInfo = true


# pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[markup]
defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      lineos = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

    [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startLevel = 2

#    [markup.highlight]
#      codeFences = true
#      guessSyntax = false
#      hl_Lines = ""
#      lineNoStart = 1
#      lineNos = true
#      lineNumbersInTable = true
#      noClasses = true
#      style = "monokai"
#      tabWidth = 4

# disqusShortname = "yourdiscussshortname"

[params]
    # author = "不可思議"
    #description = "Jiyu's personal website"
    keywords = "blog,developer,personal"
    info = "Rejoice in hope, be patient in tribulation, be constant in prayer.  Romans 12:12"
    avatarurl = "images/fencer.jpg"
    # gravatar = "yanchiyu@outlook.com"
    # footercontent = "From this world to that which is to come."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true
    since = 2019

    rtl = false
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
     colorscheme = "light"
    #  colorScheme = "auto"
    hidecolorschemetoggle = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    customCSS = ["css/custom.css"]

    # Custom JS
    customJS = ["js/copy-code-button.js"]




[params.utterances]
enable = true
repo = "Anderbone/hugo-blog-utterances"
issueTerm = "pathname"
theme = "github-light"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/Anderbone/"

# [[params.social]]
#     name = "Twitter"
#     icon = "fa fa-twitter"
#     weight = 2
#     url = "https://twitter.com/Anderesurrect/"

#[[params.social]]
#    name = "Instagram"
#    icon = "fa fa-instagram"
#    weight = 6
#    url = "https://www.instagram.com/yan.jiyu/"

 [[params.social]]
     name = "LinkedIn"
     icon = "fa fa-linkedin"
     weight = 4
     url = "https://www.linkedin.com/in/jiyu-yan/"

[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 5
    url = "mailto:yn.jiyu@gmail.com"

#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 6
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

#            [[languages.en.menu.main]]
#            name = "About"
#            weight = 1
#            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Dev"
            weight = 2
            url = "dev/"

            [[languages.en.menu.main]]
            name = "Leetcode"
            weight = 3
            url = "leetcode/"

           # [[languages.en.menu.main]]
           # name = "Contact me"
           # weight = 5
           # url = "contact/"


    [languages.zh]
        languagename = "中文"
        title = "Jiyu"

        [languages.zh.params]
            # author = "不可思議"
            info = "秋收已过，夏季已完，我们还未得救！-- 耶利米书 8:20"
#            keywords = "blog,developer,personal"
#            footercontent = "Coloque algum texto aqui."

        [languages.zh.menu]

#            [[languages.zh-cn.menu.main]]
#            name = "关于"
#            weight = 1
#            url = "about/"

            [[languages.zh.menu.main]]
            name = "随笔"
            weight = 1
            url = "/zh/posts/"

            [[languages.zh.menu.main]]
            name = "开发"
            weight = 2
            url = "/zh/dev/"

#            [[languages.zh.menu.main]]
#            name = "leetcode"
#            weight = 3
#            url = "/zh/leetcode/"
